/**
 * stackweld share <stackId> — Generate a shareable URL for a saved stack.
 * stackweld import-url <url> — Import a stack from a share URL.
 *
 * Stack data is encoded in the URL hash — no server needed.
 */

import {
  deserializeStack,
  extractFromShareUrl,
  generateShareUrl,
  type StackProfile,
  type StackTechnology,
} from "@stackweld/core";
import chalk from "chalk";
import { Command } from "commander";
import { getStackEngine } from "../ui/context.js";
import { box, formatStackRow, formatValidation, info } from "../ui/format.js";

export const shareCommand = new Command("share")
  .description("Generate a shareable URL for a saved stack")
  .argument("<id>", "Stack ID")
  .option("--base-url <url>", "Custom base URL", "https://stackweld.dev/s/#")
  .action((id: string, opts) => {
    const engine = getStackEngine();
    const stack = engine.get(id);

    if (!stack) {
      console.error(chalk.red(`Stack "${id}" not found.`));
      process.exit(1);
    }

    const shareable = {
      name: stack.name,
      profile: stack.profile,
      technologies: stack.technologies.map((t) => ({
        id: t.technologyId,
        version: t.version || undefined,
        port: t.port,
      })),
    };

    const url = generateShareUrl(shareable, opts.baseUrl);

    const content = [
      "",
      `  ${chalk.cyan(url)}`,
      "",
      `  Share this URL ${chalk.dim("\u2014")} the recipient can`,
      `  import it with:`,
      `  ${chalk.white("stackweld import-url <url>")}`,
      "",
      `  No server needed ${chalk.dim("\u2014")} stack data is`,
      `  encoded in the URL itself.`,
      "",
    ].join("\n");

    console.log("");
    console.log(box(content, `Stack Shared: ${stack.name}`));
    console.log("");
  });

export const importUrlCommand = new Command("import-url")
  .description("Import a stack from a share URL")
  .argument("<url>", "Share URL generated by stackweld share")
  .option("--json", "Output result as JSON")
  .action((url: string, opts) => {
    let encoded: string;
    try {
      encoded = extractFromShareUrl(url);
    } catch {
      console.error(
        chalk.red("Invalid share URL. Expected format: https://stackweld.dev/s/#<data>"),
      );
      process.exit(1);
    }

    let shareable: ReturnType<typeof deserializeStack>;
    try {
      shareable = deserializeStack(encoded);
    } catch {
      console.error(chalk.red("Failed to decode stack from URL. The data may be corrupted."));
      process.exit(1);
    }

    const engine = getStackEngine();

    const technologies: StackTechnology[] = shareable.technologies.map((t) => ({
      technologyId: t.id,
      version: t.version || "latest",
      port: t.port,
    }));

    const { stack, validation } = engine.create({
      name: shareable.name,
      profile: (shareable.profile as StackProfile) || "standard",
      technologies,
    });

    console.log(formatValidation(validation));
    console.log("");

    if (opts.json) {
      console.log(JSON.stringify({ stack, validation }, null, 2));
    } else {
      console.log(formatStackRow(stack));
      console.log("");
      console.log(info(`Imported "${stack.name}" from shared URL`));
      console.log("");
    }
  });
