import type { Template } from "@stackpilot/core";

export const expressApi: Template = {
  id: "express-api",
  name: "Express API",
  description:
    "Production-ready Express.js REST API with TypeScript, Prisma, PostgreSQL, Redis, and Docker",
  technologyIds: [
    "express",
    "nodejs",
    "typescript",
    "prisma",
    "postgresql",
    "redis",
    "docker",
  ],
  profile: "production",
  scaffoldSteps: [
    {
      name: "Create project directory",
      command: "mkdir -p {{projectName}}/src",
    },
    {
      name: "Initialize Node.js project",
      command: "cd {{projectName}} && npm init -y",
    },
    {
      name: "Install dependencies",
      command:
        "cd {{projectName}} && npm install express cors helmet dotenv ioredis @prisma/client",
    },
    {
      name: "Install dev dependencies",
      command:
        "cd {{projectName}} && npm install -D typescript @types/node @types/express @types/cors tsx prisma",
    },
    {
      name: "Initialize TypeScript",
      command: "cd {{projectName}} && npx tsc --init --outDir dist --rootDir src --strict --esModuleInterop --resolveJsonModule",
    },
    {
      name: "Initialize Prisma",
      command: "cd {{projectName}} && npx prisma init --datasource-provider postgresql",
    },
  ],
  overrides: [
    {
      path: ".env.example",
      content: [
        "PORT=3000",
        "NODE_ENV=development",
        "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/{{projectName}}",
        "REDIS_URL=redis://localhost:6379",
        "CORS_ORIGIN=http://localhost:5173",
      ].join("\n"),
    },
    {
      path: "docker-compose.yml",
      content: [
        "services:",
        "  db:",
        "    image: postgres:17",
        "    restart: unless-stopped",
        "    ports:",
        '      - "5432:5432"',
        "    environment:",
        "      POSTGRES_USER: postgres",
        "      POSTGRES_PASSWORD: postgres",
        "      POSTGRES_DB: {{projectName}}",
        "    volumes:",
        "      - pgdata:/var/lib/postgresql/data",
        "    healthcheck:",
        '      test: ["CMD-SHELL", "pg_isready -U postgres"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "  redis:",
        "    image: redis:7-alpine",
        "    restart: unless-stopped",
        "    ports:",
        '      - "6379:6379"',
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "volumes:",
        "  pgdata:",
      ].join("\n"),
    },
    {
      path: "Dockerfile",
      content: [
        "FROM node:22-alpine AS builder",
        "WORKDIR /app",
        "COPY package*.json ./",
        "RUN npm ci",
        "COPY . .",
        "RUN npx prisma generate",
        "RUN npx tsc",
        "",
        "FROM node:22-alpine",
        "WORKDIR /app",
        "COPY package*.json ./",
        "RUN npm ci --omit=dev",
        "COPY --from=builder /app/dist ./dist",
        "COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma",
        "COPY prisma ./prisma",
        "EXPOSE 3000",
        'CMD ["node", "dist/index.js"]',
      ].join("\n"),
    },
    {
      path: "src/index.ts",
      content: [
        'import express from "express";',
        'import cors from "cors";',
        'import helmet from "helmet";',
        'import dotenv from "dotenv";',
        "",
        "dotenv.config();",
        "",
        "const app = express();",
        "const port = process.env.PORT || 3000;",
        "",
        "app.use(helmet());",
        "app.use(cors({ origin: process.env.CORS_ORIGIN }));",
        "app.use(express.json());",
        "",
        'app.get("/health", (_req, res) => {',
        '  res.json({ status: "ok" });',
        "});",
        "",
        "app.listen(port, () => {",
        "  console.log(`Server running on port ${port}`);",
        "});",
      ].join("\n"),
    },
  ],
  hooks: [
    {
      timing: "post-scaffold",
      name: "Generate Prisma client",
      command: "cd {{projectName}} && npx prisma generate",
      description: "Generate the Prisma client from schema",
      requiresConfirmation: false,
    },
  ],
  variables: {
    projectName: "my-express-api",
  },
};
