import type { Template } from "@stackpilot/core";

export const goMicroservice: Template = {
  id: "go-microservice",
  name: "Go Microservice",
  description:
    "Lightweight Go microservice with Gin, PostgreSQL, Docker, and health checks",
  technologyIds: [
    "go",
    "gin",
    "postgresql",
    "redis",
    "docker",
  ],
  profile: "production",
  scaffoldSteps: [
    {
      name: "Create project directory",
      command: "mkdir -p {{projectName}}/{cmd/server,internal/{handlers,models,middleware},pkg}",
    },
    {
      name: "Initialize Go module",
      command: "cd {{projectName}} && go mod init {{moduleName}}",
    },
    {
      name: "Install dependencies",
      command:
        "cd {{projectName}} && go get github.com/gin-gonic/gin github.com/lib/pq github.com/redis/go-redis/v9 github.com/joho/godotenv",
    },
  ],
  overrides: [
    {
      path: ".env.example",
      content: [
        "PORT=8080",
        "GIN_MODE=debug",
        "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/{{projectName}}",
        "REDIS_URL=redis://localhost:6379/0",
      ].join("\n"),
    },
    {
      path: "docker-compose.yml",
      content: [
        "services:",
        "  db:",
        "    image: postgres:17",
        "    restart: unless-stopped",
        "    ports:",
        '      - "5432:5432"',
        "    environment:",
        "      POSTGRES_USER: postgres",
        "      POSTGRES_PASSWORD: postgres",
        "      POSTGRES_DB: {{projectName}}",
        "    volumes:",
        "      - pgdata:/var/lib/postgresql/data",
        "    healthcheck:",
        '      test: ["CMD-SHELL", "pg_isready -U postgres"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "  redis:",
        "    image: redis:7-alpine",
        "    restart: unless-stopped",
        "    ports:",
        '      - "6379:6379"',
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "volumes:",
        "  pgdata:",
      ].join("\n"),
    },
    {
      path: "Dockerfile",
      content: [
        "FROM golang:1.23-alpine AS builder",
        "WORKDIR /app",
        "COPY go.mod go.sum ./",
        "RUN go mod download",
        "COPY . .",
        "RUN CGO_ENABLED=0 go build -o server ./cmd/server",
        "",
        "FROM alpine:3.19",
        "RUN apk --no-cache add ca-certificates",
        "WORKDIR /app",
        "COPY --from=builder /app/server .",
        'EXPOSE 8080',
        'CMD ["./server"]',
      ].join("\n"),
    },
    {
      path: "cmd/server/main.go",
      content: [
        "package main",
        "",
        "import (",
        '\t"log"',
        '\t"os"',
        "",
        '\t"github.com/gin-gonic/gin"',
        '\t"github.com/joho/godotenv"',
        ")",
        "",
        "func main() {",
        "\tgodotenv.Load()",
        "",
        '\tport := os.Getenv("PORT")',
        "\tif port == \"\" {",
        '\t\tport = "8080"',
        "\t}",
        "",
        "\tr := gin.Default()",
        "",
        '\tr.GET("/health", func(c *gin.Context) {',
        '\t\tc.JSON(200, gin.H{"status": "ok"})',
        "\t})",
        "",
        '\tlog.Fatal(r.Run(":" + port))',
        "}",
      ].join("\n"),
    },
  ],
  hooks: [
    {
      timing: "post-scaffold",
      name: "Tidy Go modules",
      command: "cd {{projectName}} && go mod tidy",
      description: "Clean up Go module dependencies",
      requiresConfirmation: false,
    },
  ],
  variables: {
    projectName: "my-go-service",
    moduleName: "github.com/user/my-go-service",
  },
};
