import type { Template } from "@stackpilot/core";

export const laravelApp: Template = {
  id: "laravel-app",
  name: "Laravel App",
  description:
    "Full-stack Laravel application with MySQL, Redis, and Docker",
  technologyIds: [
    "laravel",
    "php",
    "mysql",
    "redis",
    "docker",
  ],
  profile: "standard",
  scaffoldSteps: [
    {
      name: "Create Laravel project",
      command: "composer create-project laravel/laravel {{projectName}}",
    },
  ],
  overrides: [
    {
      path: ".env.example",
      content: [
        "APP_NAME={{projectName}}",
        "APP_ENV=local",
        "APP_KEY=",
        "APP_DEBUG=true",
        "APP_URL=http://localhost:8000",
        "",
        "DB_CONNECTION=mysql",
        "DB_HOST=127.0.0.1",
        "DB_PORT=3306",
        "DB_DATABASE={{projectName}}",
        "DB_USERNAME=root",
        "DB_PASSWORD=secret",
        "",
        "REDIS_HOST=127.0.0.1",
        "REDIS_PASSWORD=null",
        "REDIS_PORT=6379",
        "",
        "CACHE_STORE=redis",
        "SESSION_DRIVER=redis",
        "QUEUE_CONNECTION=redis",
      ].join("\n"),
    },
    {
      path: "docker-compose.yml",
      content: [
        "services:",
        "  mysql:",
        "    image: mysql:8.4",
        "    restart: unless-stopped",
        "    ports:",
        '      - "3306:3306"',
        "    environment:",
        "      MYSQL_ROOT_PASSWORD: secret",
        "      MYSQL_DATABASE: {{projectName}}",
        "    volumes:",
        "      - mysqldata:/var/lib/mysql",
        "    healthcheck:",
        '      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]',
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "  redis:",
        "    image: redis:7-alpine",
        "    restart: unless-stopped",
        "    ports:",
        '      - "6379:6379"',
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "volumes:",
        "  mysqldata:",
      ].join("\n"),
    },
  ],
  hooks: [
    {
      timing: "post-scaffold",
      name: "Generate app key",
      command: "cd {{projectName}} && php artisan key:generate",
      description: "Generate Laravel application encryption key",
      requiresConfirmation: false,
    },
    {
      timing: "post-scaffold",
      name: "Run migrations",
      command: "cd {{projectName}} && php artisan migrate",
      description: "Run database migrations (requires running MySQL)",
      requiresConfirmation: true,
    },
  ],
  variables: {
    projectName: "my-laravel-app",
  },
};
