import type { Template } from "@stackpilot/core";

export const pythonAiLab: Template = {
  id: "python-ai-lab",
  name: "Python AI Lab",
  description: "Python ML/AI development environment with FastAPI, PostgreSQL, Redis, and Docker",
  technologyIds: ["python", "fastapi", "postgresql", "redis", "docker"],
  profile: "production",
  scaffoldSteps: [
    {
      name: "Create project structure",
      command:
        "mkdir -p {{projectName}}/{app/{api,models,services,ml},tests,notebooks,data/{raw,processed}}",
    },
    {
      name: "Setup Python virtual environment",
      command: "python3 -m venv {{projectName}}/.venv",
    },
    {
      name: "Install dependencies",
      command:
        "{{projectName}}/.venv/bin/pip install fastapi uvicorn[standard] sqlalchemy[asyncio] asyncpg redis python-dotenv pydantic-settings alembic",
    },
    {
      name: "Install ML dependencies",
      command: "{{projectName}}/.venv/bin/pip install numpy pandas scikit-learn jupyter matplotlib",
    },
  ],
  overrides: [
    {
      path: ".env.example",
      content: [
        "# API",
        "APP_HOST=0.0.0.0",
        "APP_PORT=8000",
        "APP_ENV=development",
        "",
        "# Database",
        "DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/{{projectName}}",
        "",
        "# Redis",
        "REDIS_URL=redis://localhost:6379",
        "",
        "# ML",
        "MODEL_PATH=./data/models",
        "OPENAI_API_KEY=sk-...",
      ].join("\n"),
    },
    {
      path: "docker-compose.yml",
      content: [
        "services:",
        "  db:",
        "    image: postgres:17",
        "    restart: unless-stopped",
        "    ports:",
        '      - "5432:5432"',
        "    environment:",
        "      POSTGRES_USER: postgres",
        "      POSTGRES_PASSWORD: postgres",
        "      POSTGRES_DB: {{projectName}}",
        "    volumes:",
        "      - pgdata:/var/lib/postgresql/data",
        "    healthcheck:",
        '      test: ["CMD-SHELL", "pg_isready -U postgres"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "  redis:",
        "    image: redis:7-alpine",
        "    restart: unless-stopped",
        "    ports:",
        '      - "6379:6379"',
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
        "volumes:",
        "  pgdata:",
      ].join("\n"),
    },
    {
      path: "requirements.txt",
      content: [
        "fastapi>=0.115",
        "uvicorn[standard]>=0.32",
        "sqlalchemy[asyncio]>=2.0",
        "asyncpg>=0.30",
        "redis>=5.0",
        "python-dotenv>=1.0",
        "pydantic-settings>=2.0",
        "alembic>=1.14",
        "numpy>=2.0",
        "pandas>=2.2",
        "scikit-learn>=1.5",
        "jupyter>=1.1",
        "matplotlib>=3.9",
      ].join("\n"),
    },
    {
      path: "app/__init__.py",
      content: "",
    },
    {
      path: "app/main.py",
      content: [
        "from fastapi import FastAPI",
        "from dotenv import load_dotenv",
        "",
        "load_dotenv()",
        "",
        'app = FastAPI(title="{{projectName}}", version="0.1.0")',
        "",
        "",
        '@app.get("/health")',
        "async def health():",
        '    return {"status": "ok"}',
      ].join("\n"),
    },
    {
      path: "Dockerfile",
      content: [
        "FROM python:3.12-slim",
        "WORKDIR /app",
        "COPY requirements.txt .",
        "RUN pip install --no-cache-dir -r requirements.txt",
        "COPY . .",
        "EXPOSE 8000",
        'CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]',
      ].join("\n"),
    },
  ],
  hooks: [
    {
      timing: "post-scaffold",
      name: "Freeze requirements",
      command: "cd {{projectName}} && .venv/bin/pip freeze > requirements.lock",
      description: "Generate locked requirements file",
      requiresConfirmation: false,
    },
    {
      timing: "post-scaffold",
      name: "Initialize Alembic",
      command: "cd {{projectName}} && .venv/bin/alembic init alembic",
      description: "Initialize Alembic for database migrations",
      requiresConfirmation: false,
    },
  ],
  variables: {
    projectName: "my-ai-lab",
  },
};
